const records = [
  {
    altitudeInt: 40,
    commonNme: 'Laughing Kookaburra',
    conservationStatus: '         ',
    latLongAccuracyddNum: 900,
    latitudeddNum: -37.80778,
    longitudeddNum: 144.97333,
    observerFullName: 'Cameron Williams',
    projectId: 1,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'General observations',
    scientificDisplayNme: 'Dacelo novaeguineae',
    siteId: 625883,
    siteLocationDesc: 'Cnr Victoria Parade & Nicholson Street, East Melbourne',
    surveyId: 952573,
    surveyStartSdt: 1252332000000,
    taxonId: 10322,
    totalCountInt: 1,
  },
  {
    altitudeInt: 35,
    commonNme: 'Spreading Amaranth',
    conservationStatus: '        *',
    coverAbundanceCde: '+',
    latLongAccuracyddNum: 15,
    latitudeddNum: -37.80778,
    longitudeddNum: 144.97306,
    observerFullName: 'David Cameron',
    originCategoryCde: '*',
    projectId: 938,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Amaranthus deflexus',
    siteId: 288548,
    siteLocationDesc: 'Centre about 1 km SW of FITZROY',
    siteNme: 'I6079500',
    surveyId: 288548,
    surveyStartSdt: 1304344800000,
    taxonId: 500191,
  },
  {
    altitudeInt: 20,
    commonNme: 'Laughing Kookaburra',
    conservationStatus: '         ',
    latLongAccuracyddNum: 900,
    latitudeddNum: -37.80861,
    longitudeddNum: 144.97333,
    observerFullName: "Martin O'Brien",
    projectId: 1,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'General observations',
    scientificDisplayNme: 'Dacelo novaeguineae',
    siteId: 616006,
    siteLocationDesc: 'Evelyn Place; East Melbourne',
    surveyId: 942708,
    surveyStartSdt: 1216303200000,
    taxonId: 10322,
    totalCountInt: 1,
    typeCde: 'o',
  },
  {
    altitudeInt: 40,
    commonNme: 'Yellow-tailed Black-Cockatoo',
    conservationStatus: '         ',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80857,
    longitudeddNum: 144.97321,
    observerFullName: 'Cameron Williams',
    projectId: 1,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'General observations',
    scientificDisplayNme: 'Calyptorhynchus funereus',
    siteId: 629670,
    siteLocationDesc: '8 Nicholson Street, East Melbourne',
    surveyId: 956360,
    surveyStartSdt: 1275919200000,
    taxonId: 10267,
    totalCountInt: 0,
    typeCde: 's',
  },
  {
    commonNme: 'Rainbow Lorikeet',
    conservationStatus: '         ',
    latLongAccuracyddNum: 20,
    latitudeddNum: -37.8103,
    longitudeddNum: 144.9739,
    observerFullName: 'Melanie Hardie',
    projectId: 1,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'General observations',
    scientificDisplayNme: 'Trichoglossus haematodus',
    siteId: 620844,
    siteLocationDesc: 'Spring Street,  Melbourne',
    siteNme: 'Parliament Gardens',
    surveyId: 967876,
    surveyStartSdt: 1336917600000,
    taxonId: 10254,
    totalCountInt: 2,
    typeCde: 's',
  },
  {
    commonNme: 'White-browed Scrubwren',
    conservationStatus: '         ',
    latLongAccuracyddNum: 20,
    latitudeddNum: -37.8103,
    longitudeddNum: 144.9739,
    observerFullName: 'David Clark',
    projectId: 1,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'General observations',
    scientificDisplayNme: 'Sericornis frontalis',
    siteId: 620844,
    siteLocationDesc: 'Spring Street,  Melbourne',
    siteNme: 'Parliament Gardens',
    surveyId: 947539,
    surveyStartSdt: 1229000400000,
    taxonId: 10488,
    totalCountInt: 1,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490614,
    surveyStartSdt: 1057500000000,
    taxonId: 11280,
    totalCountInt: 4,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490616,
    surveyStartSdt: 1056549600000,
    taxonId: 11280,
    totalCountInt: 6,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490394,
    surveyStartSdt: 1059314400000,
    taxonId: 11280,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490611,
    surveyStartSdt: 1057068000000,
    taxonId: 11280,
    totalCountInt: 2,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490396,
    surveyStartSdt: 1059487200000,
    taxonId: 11280,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490617,
    surveyStartSdt: 1057240800000,
    taxonId: 11280,
    totalCountInt: 8,
    typeCde: 's',
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    conservationStatus: 'VU vu L  ',
    dseAdvisoryCde: 'vu',
    epbcCode: 'VU',
    extraCde: 'c',
    ffgListingCde: 'L',
    latLongAccuracyddNum: 100,
    latitudeddNum: -37.80995,
    longitudeddNum: 144.97294,
    observerFullName: 'Rodney Van der Ree',
    projectId: 2565,
    reliabilityCde: 'acc',
    restrictedAccessCde: 'n',
    samplingMethodCde: 'Incidental',
    scientificDisplayNme: 'Pteropus poliocephalus',
    siteId: 493880,
    siteLocationDesc: 'Melbourne ParliamentGardens',
    surveyId: 490395,
    surveyStartSdt: 1059400800000,
    taxonId: 11280,
    typeCde: 's',
  },
];

const speciesList = [
  {
    commonNme: 'Laughing Kookaburra',
    scientificDisplayNme: 'Dacelo novaeguineae',
    taxonId: 10322,
    totalCountInt: 2,
  },
  {
    commonNme: 'Spreading Amaranth',
    scientificDisplayNme: 'Amaranthus deflexus',
    taxonId: 500191,
    totalCountInt: 1,
  },
  {
    commonNme: 'Yellow-tailed Black-Cockatoo',
    scientificDisplayNme: 'Calyptorhynchus funereus',
    taxonId: 10267,
    totalCountInt: 0,
  },
  {
    commonNme: 'Rainbow Lorikeet',
    scientificDisplayNme: 'Trichoglossus haematodus',
    taxonId: 10254,
    totalCountInt: 2,
  },
  {
    commonNme: 'White-browed Scrubwren',
    scientificDisplayNme: 'Sericornis frontalis',
    taxonId: 10488,
    totalCountInt: 1,
  },
  {
    commonNme: 'Grey-headed Flying-fox',
    scientificDisplayNme: 'Pteropus poliocephalus',
    taxonId: 11280,
    totalCountInt: 23,
  },
];

export { records, speciesList };
